- name: Install System Packages
  become: true
  pacman:
    name: 
      - "xorg"
      - "xorg-xinit"
      - "lsof"
      - "i3"
      - "i3lock"
      - "i3blocks"
      - "pavucontrol"
      - "pulseaudio"
      - "picom"
      - "maim"
      - "xautolock"
      - "xss-lock"
      - "networkmanager"
      - "networkmanager-openvpn"
      - "networkmanager-pptp"
      - "base-devel"
  tags:
    - install
    - core

- name: Install System Utilities
  become: true
  pacman:
    name:
      - "curl"
      - "unzip"
      - "htop"
      - "dunst"
      - "thunar"
      - "lxappearance"
      - "rofi"
      - "nitrogen"
      - "xarchiver"
      - "sysstat"
      - "man-pages"
      - "keychain"
      - "nm-connection-editor"
      - "lm_sensors"
      - "alsa-utils"
  tags:
    - install
    - core
    - utilities

