- name: Installing stow
  become: true
  pacman:
    name: stow
  tags:
    - install
    - dotfiles

- name: Cloning .dotfiles
  git:
    repo: 'https://github.com/AntPeixe/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    recursive: yes
    update: yes
    version: main
  tags:
    - install
    - dotfiles

- name: Stow dotfiles
  shell: cd $HOME/dotfiles && ./install.sh
  tags:
    - install
    - dotfiles

